apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dashboard-config.yaml
  - data-science-cluster.yaml
  - dscInitialization.yaml
  - namespace.yaml
  - operator-group.yaml
  - subscription.yaml
