apiVersion: v1
kind: ConfigMap
metadata:
  name: maven-settings-xml
  namespace: devspaces
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspaces-config
  annotations:
    controller.devfile.io/mount-as: subpath
    controller.devfile.io/mount-path: /usr/share/maven/conf
data:
  settings.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <settings xmlns="http://maven.apache.org/SETTINGS/1.2.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.2.0 https://maven.apache.org/xsd/settings-1.2.0.xsd">
      <mirrors>
        <mirror>
          <id>maven-public</id>
          <name>maven-public</name>
          <url>https://nexus-web.{{ .Values.domain }}/repository/maven-public/</url>
          <mirrorOf>*</mirrorOf>
        </mirror>
      </mirrors>
      <profiles>
        <profile>
          <id>maven-nexus-repo</id>
          <repositories>
            <repository>
              <id>maven-public</id>
              <name>maven-public</name>
              <url>https://nexus-web.{{ .Values.domain }}/repository/maven-public/</url>
            </repository>
          </repositories>
        </profile>
      </profiles>
      <activeProfiles>
        <activeProfile>maven-nexus-repo</activeProfile>
      </activeProfiles>
    </settings>
