apiVersion: v1
kind: Namespace
metadata:
  name: openshift-pipelines-operator-rh
  annotations:
    argocd.argoproj.io/sync-wave: "16"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec: {}