apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: nexus
  namespace: nexus
spec:
  applicationMenu:
    section: Artifacts Repository
  href: "https://nexus-web.apps.rosa.<path:secret/data/rosa-domain#domain>"
  location: ApplicationMenu
  text: Nexus Repository Web Dashboard
