apiVersion: v1
kind: ConfigMap
metadata:
  name: global-cluster-params
data:
  CLUSTER_NAME: "DUMMY_CLUSTER"
  ROSA_DOMAIN: "DUMMY_DOMAIN"
  # New variables for Keycloak Client Redirects
  OAUTH_REDIRECT_URI: "DUMMY_OAUTH"
  BACKSTAGE_HTTPS_URI: "DUMMY_BS_HTTPS"
  BACKSTAGE_HTTP_URI: "DUMMY_BS_HTTP"
  GITEA_REDIRECT_URI: "DUMMY_GITEA"