apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - client-openshift.yaml
  - keycloak.yaml
  - namespace.yaml
  - operator-group.yaml
  - pull-secret-client-openshift.yaml
  - pull-secret-credential-keycloak.yaml
  - pull-secret-intial-users.yaml
  - pull-secret-rosa-token.yaml
  - push-secret-client-openshift.yaml
  - push-secret-credential-keycloak.yaml
  - realm-openshift.yaml
  - subscription.yaml
