apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "38"
  name: keycloak
  namespace: keycloak
spec:
  targetNamespaces:
  - keycloak
  - openshift-config
  upgradeStrategy: Default