apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: gitea
  namespace: gitea
spec:
  applicationMenu:
    section: Artifacts Repository
  href: "https://gitea.{{ .Values.domain }}"
  location: ApplicationMenu
  text: Gitea Dashboard
