apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitea-admin-job-rb
  namespace: gitea
  annotations:
    argocd.argoproj.io/sync-wave: "52"
subjects:
- kind: ServiceAccount
  name: gitea-admin-job-sa
roleRef:
  kind: Role
  name: gitea-admin-job-role
  apiGroup: rbac.authorization.k8s.io
