apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - domain-configmap.yaml
  - console-link.yaml

replacements:
  - source:
      kind: ConfigMap
      name: global-domain-config
      fieldPath: data.ROSA_DOMAIN
    targets:
      # 1. Patch the ConsoleLink
      - select:
          kind: ConsoleLink
          name: gitea
        fieldPaths:
          - spec.href
        options:
          delimiter: "PLACEHOLDER_DOMAIN"
          
      # 2. Patch the Route
      - select:
          kind: Route
          name: gitea-ui
        fieldPaths:
          - spec.host
        options:
          delimiter: "PLACEHOLDER_DOMAIN"
          
      # 3. FUTURE MANIFESTS GO HERE
      # - select:
      #     kind: SomeOtherResource
      #     name: some-name
      #   fieldPaths:
      #     - spec.some.field
      #   options:
      #     delimiter: "PLACEHOLDER_DOMAIN"
