apiVersion: v1
kind: Namespace
metadata:
  name: openshift-serverless
  annotations:
    argocd.argoproj.io/sync-wave: "22"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec: {}