apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prepull-udi-image
  namespace: devspaces-build
  labels:
    app: prepull-udi
spec:
  selector:
    matchLabels:
      name: prepull-udi
  template:
    metadata:
      labels:
        name: prepull-udi
    spec:
      tolerations:
      - operator: Exists
      containers:
      - name: udi-container
        image: image-registry.openshift-image-registry.svc:5000/openshift/udi-rhel9
        command: ["/bin/sh", "-c", "sleep infinity"]
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 100Mi
