apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: password
  namespace: minio-operator
  annotations:
    argocd.argoproj.io/sync-wave: "51"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  length: 10
  symbols: 0
  digits: 4
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "minio-credentials"
  namespace: minio-operator
spec:
  refreshInterval: "0" # Change to "1h" if you want the password to rotate
  target:
    name: minio-credentials
    template:
      engineVersion: v2
      data:
        # Hardcode the static username here
        MINIO_ROOT_USER: "minioadmin"
        # Pull the generated password from the sourceRef below
        MINIO_ROOT_PASSWORD: "{{ .password_gen }}"
  data:
    - secretKey: password_gen
      sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: "password"