apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment-minio.yaml
  - generate-credentials.yaml
  - push-secret-minio-creds.yaml
  - pvc.yaml
  - route-api.yaml
  - route-console.yaml
  - service-api.yaml
  - service-console.yaml
