apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - che-cluster.yaml
  - maven-settings-xml.yaml
  - namespace-build.yaml
  - namespace.yaml
  - npm-global-config.yaml
  # - prepull-dotnet-python.yaml
  # - prepull-udi.yaml
  - roles-template.yaml
  - subscription.yaml
