apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - chains-config.yaml
  - operatorGroup.yaml
  - rbac-container-builds.yaml
  # - secrets-cosign-keys.yaml
  - subscription.yaml
