apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-client-secret-rosa
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "40"
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-rosa-token
    creationPolicy: Owner
  data:
    - secretKey: ROSA_TOKEN
      remoteRef:
        key: rosa-token
        property: token
    - secretKey: AWS_ACCESS_ID
      remoteRef:
        key: aws-credentials
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: aws-credentials
        property: AWS_SECRET_ACCESS_KEY