apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-client-secret-pull
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "40"
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-client-secret
    template:
      engineVersion: v2
      data:
        clientSecret: "{{ .CLIENT_SECRET }}"
  data:
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: keycloak-client-secret-openshift
        property: CLIENT_SECRET