apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: kubernetes-secret-store
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '1'
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: external-secrets-kubeaccess-sa
          namespace: secrets-manager
      remoteNamespace: secrets-manager
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          namespace: secrets-manager
          type: ConfigMap
        url: 'https://kubernetes.default.svc'