resources:
  - namespace.yaml
  - externalSecretsConfig.yaml
  - subscription.yaml
  - clusterSecretStore.yaml
  # - netPolAllowEgressToVault.yaml
  - serviceAccount.yaml
  - operatorGroup.yaml
  - kubernetesSecretStore.yaml