apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "54"
spec:
  chart:
    values:
      certmanager:
        install: true
      certmanager-issuer:
        email: "admin@openshift.com"
      # https://docs.gitlab.com/charts/charts/globals/ for settings
      global:
        edition: ce
        hosts:
          domain: "<path:secret/data/rosa-domain#domain"
        appConfig:
          # https://docs.gitlab.com/topics/autodevops/
          autoDevOps:
            enabled: false
          # https://docs.gitlab.com/integration/omniauth/#configure-common-settings
          omniauth:
            enabled: true
            allowSingleSignOn: ["openid_connect"]
            blockAutoCreatedUsers: false
            autoLinkUser: ['openid_connect']
            providers:
              - secret: keycloak-oidc-client
        runner:
          registrationToken:
            secret: runner-secret
        ingress:
          enabled: false
      gitlab-runner:
        runners:
          config: |
            [[runners]]
              [runners.kubernetes]
              image = "ubuntu:22.04"
    version: "9.11.4"
