apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: gitlab-system
  namespace: gitlab-system
  annotations:
    argocd.argoproj.io/sync-wave: "53"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetNamespaces:
    - gitlab-system